[package]
name = "glove"
version = "0.1.0"
edition = "2021"

[dependencies]
defer = "0.2"
libc = "0.2"
rustix = { version = "0.38", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "net", "fs"] }
